version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload 